version: '3.6'
services:
  zerotier-aio-zh:
    image: dockerproxy.com/niliaerith/zerotier-aio-zh:2023-09-05
    container_name: zerotier-aio-zh
    hostname: zerotier-aio-zh
    restart: always
    cap_add:
      - ALL
    devices:
      - /dev/net/tun
    network_mode: host
    volumes:
      - /root/zerotier-aio-zh/opt/key-networks/ztncui/etc:/opt/key-networks/ztncui/etc
      - /root/zerotier-aio-zh/var/lib/zerotier-one:/var/lib/zerotier-one
      - /root/zerotier-aio-zh/etc/zt-mkworld:/etc/zt-mkworld
    environment:
      - TZ=Asia/Shanghai
      - AUTOGEN_PLANET=0
      - NODE_ENV=production
      - HTTPS_HOST=xxx.xxx.xxx.xxx
      - HTTPS_PORT=3443
      - HTTP_PORT=3000
      - HTTP_ALL_INTERFACES=yes
      - MYDOMAIN=ztncui.docker.test
      - ZTNCUI_PASSWD=YourPassWD
      - MYADDR=PublicIP
    privileged: true
